version: 0.2
 
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Install pnpm
      - npm install pnpm -g
      - echo Install project dependencies
      - pnpm install
  build:
    commands:
      - echo Start build
      - pnpm build
  post_build:
    commands:
      - cp -R node_modules/ dist/node_modules
artifacts:
  files:
    - 'node_modules/**/*'
    - 'dist/**/*'
    - 'Procfile'
    - 'package.json'